"""
Migration Error Correction Agent
=================================
Takes the original Java code, generated Julia code, migration analysis,
risks, and detected errors — then produces corrected Julia code.

Uses an iterative correction process:
  Generate Julia → Detect errors → Correct → Detect again → Repeat
  until no critical errors remain or max retries (3) reached.

This is migration error correction, NOT the existing code remediation.
These two workflows are completely separate.
"""

import re
import json
from typing import Any, Dict, List, Optional

from google import genai
from google.genai import types

from app.core.config import settings


MAX_CORRECTION_RETRIES = 3


class MigrationErrorCorrectionAgent:
    """
    Corrects errors in Julia code generated from Java migration.
    Operates iteratively with the Error Detection Agent.
    """

    def __init__(self):
        self.client = None
        if settings.GEMINI_API_KEY and settings.GEMINI_API_KEY.strip():
            try:
                self.client = genai.Client(
                    api_key=settings.GEMINI_API_KEY,
                    http_options=types.HttpOptions(
                        timeout=90000,
                        retry_options=types.HttpRetryOptions(
                            attempts=2,
                        ),
                    ),
                )
            except Exception:
                self.client = None

    # ============================================================
    # CORRECTION LOGIC
    # ============================================================

    def _build_correction_prompt(
        self,
        java_code: str,
        julia_code: str,
        errors: List[Dict[str, Any]],
        analysis: Optional[Dict[str, Any]] = None,
        risks: Optional[List[Dict[str, Any]]] = None,
        iteration: int = 1,
    ) -> str:
        """Build the correction prompt with all context."""

        error_text = "\n".join(
            f"  {i+1}. [{e.get('type', 'ERROR')}] Line {e.get('line', '?')}: "
            f"{e.get('issue', 'Unknown')} (Severity: {e.get('severity', 'MEDIUM')})"
            for i, e in enumerate(errors)
        )

        risk_text = ""
        if risks:
            risk_text = "\nMigration Risks to consider:\n" + "\n".join(
                f"  - {r.get('risk', 'Unknown')} ({r.get('severity', 'MEDIUM')}): {r.get('suggested_resolution', '')}"
                for r in risks[:5]
            )

        return f"""You are a Julia code correction specialist. This is correction iteration {iteration}/{MAX_CORRECTION_RETRIES}.

The Julia code below was generated by migrating Java code but contains errors.
Fix ALL the detected errors while preserving the intended functionality of the original Java code.

RULES:
1. Fix all detected errors
2. Do NOT change functionality — only fix migration errors
3. Ensure the output is valid, compilable Julia code
4. Use idiomatic Julia patterns
5. Maintain 1-based indexing (Julia standard)
6. Remove any remaining Java syntax artifacts
7. Return the COMPLETE corrected Julia code, not just the changed parts

Detected errors:
{error_text}
{risk_text}

Respond with ONLY valid JSON (no markdown fences):
{{
  "corrected_julia_code": "the complete corrected Julia code",
  "corrections_made": [
    {{
      "line": <original_line_number>,
      "original": "original code",
      "corrected": "corrected code",
      "reason": "why this correction was needed"
    }}
  ]
}}

Original Java code:
```java
{java_code}
```

Current Julia code (with errors):
```julia
{julia_code}
```"""

    def correct_errors(
        self,
        java_code: str,
        julia_code: str,
        errors: List[Dict[str, Any]],
        analysis: Optional[Dict[str, Any]] = None,
        risks: Optional[List[Dict[str, Any]]] = None,
        iteration: int = 1,
    ) -> Dict[str, Any]:
        """
        Attempt to correct errors in the Julia code.

        Parameters:
            java_code: Original Java source
            julia_code: Current Julia code with errors
            errors: List of detected errors
            analysis: Migration analysis result
            risks: Migration risk analysis result
            iteration: Current correction iteration number

        Returns:
            Dictionary with corrected_julia_code and corrections_made
        """

        if not errors:
            return {
                "corrected_julia_code": julia_code,
                "corrections_made": [],
                "status": "no_errors_to_correct",
            }

        if not self.client:
            return {
                "corrected_julia_code": julia_code,
                "corrections_made": [],
                "status": "error",
                "error": "Gemini API key not configured. Cannot perform error correction.",
            }

        prompt = self._build_correction_prompt(
            java_code, julia_code, errors, analysis, risks, iteration
        )

        try:
            response = self.client.models.generate_content(
                model="gemini-2.0-flash",
                contents=prompt,
                config=types.GenerateContentConfig(
                    temperature=0.1,
                    max_output_tokens=8000,
                    response_mime_type="application/json",
                ),
            )

            text = response.text.strip()
            if text.startswith("```"):
                text = re.sub(r'^```(?:json)?\s*', '', text)
                text = re.sub(r'\s*```$', '', text)

            result = json.loads(text)

            corrected_code = result.get("corrected_julia_code", "")
            if not corrected_code.strip():
                return {
                    "corrected_julia_code": julia_code,
                    "corrections_made": [],
                    "status": "error",
                    "error": "LLM returned empty corrected code",
                }

            return {
                "corrected_julia_code": corrected_code,
                "corrections_made": result.get("corrections_made", []),
                "status": "corrected",
                "iteration": iteration,
            }

        except json.JSONDecodeError:
            # Try to extract Julia code from raw response
            raw = response.text.strip() if response and response.text else ""
            julia_match = re.search(r'```julia\s*(.*?)\s*```', raw, re.DOTALL)
            if julia_match:
                return {
                    "corrected_julia_code": julia_match.group(1).strip(),
                    "corrections_made": [{"reason": "Extracted from non-JSON response"}],
                    "status": "corrected",
                    "iteration": iteration,
                }
            return {
                "corrected_julia_code": julia_code,
                "corrections_made": [],
                "status": "error",
                "error": "Failed to parse correction response",
            }

        except Exception as e:
            return {
                "corrected_julia_code": julia_code,
                "corrections_made": [],
                "status": "error",
                "error": f"Correction failed: {str(e)}",
            }
